### PR TITLE
Update wormbase.js

### PR DESCRIPTION
**Pull request by anishagg17**
this was throwing an error in console

### CODE REVIEW

**Comment by sibyl229** [comment]
Hi @anishagg17 thanks a lot for looking into the issue with `pageInfo`! 

I'm a little surprise that it causes problem in that line, while other lines seem to be able to access properties of `pageInfo` without problem. Could you show me which page/url you encountered the issue on? Thanks!

**Comment by anishagg17** [comment]
Screenshot 2020-03-17 at 1 54 51 AM

this line caused this error

**Comment by anishagg17** [comment]
After fixing another error occurs related to pageInfo , these are specifically because there is no context chaining

Screenshot 2020-03-17 at 1 56 20 AM

**Comment by anishagg17** [comment]
@sibyl229 I have fixed more of the context errors please have a look

**Pull request closed without merging**
